version: '3.8'

services:
    postgres:
        container_name: wedding-site-db
        image: postgres:16.2
        ports:
            - 8000:5432
        environment:
            - POSTGRES_USER=${USER}
            - POSTGRES_PASSWORD=${USER}
        volumes:
            - ./local-data/postgres:/var/lib/postgresql/data:delegated
